# Mapping of symlinks.
#
# Notes:
#     __root__ will be replaced by user root directory.
#

# All non-standard directories, to create if doesn't exist.
directories:
    - __root__.pip
    - __root__.antigen
    - __root__.config/alacritty
    - __root__.config/nvim

# List of all symlinks.
links:
    __root__.zshrc:                                     zsh/zshrc
    __root__.pylintrc:                                  python/pylintrc
    __root__.tmux.conf:                                 tmux/tmux.conf
    __root__.gitconfig:                                 git/gitconfig
    __root__.gitconfig_plum:                            git/gitconfig_plum
    __root__.gitignore_global:                          git/gitignore_global
    __root__.config/alacritty/alacritty.yml:            alacritty/alacritty.yml
    __root__.config/nvim/init.vim:                      vim/init.vim
    __root__.pip/pip.conf:                              pip/pip.conf
    /usr/local/bin/localip:                             bin/localip
    /usr/local/bin/battery:                             bin/battery

# Brew packages.
brew:
    - tmux
    - git
    - python3
    - wget
    - zsh
    - fzf
    - htop
    - gotop
    - exa
    - curl
    - bash
    - gnu-sed
    - tree
    - jq
    - make
    - the_silver_searcher  # ag
    - ripgrep
    - neovim

# Brew cask installs.
cask:
    - tableplus
    - docker
    - alacritty
    - rectangle
    - firefox-developer-edition
    - alfred
    - spotify
    - bartender
    - bitbar
    - flux
    - imageoptim
    - pritunl
    - sip
    - transmission
    - ngrok
    - google-chrome
